# Default Configuration

spring:
    profiles:
        active: dev

    main:
        banner-mode: "off"

server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false


---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

eureka:
    server:
        wait-time-in-ms-when-sync-empty: 5

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production
